#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root."
   exit 1
fi

if [ -z "$1" ]; then
    echo "Error: No public key provided."
    exit 1
fi

# Check if the argument is "list"
if [ "$1" == "list" ]; then
    cat /etc/tunnel-guard/.ssh/authorized_keys
    exit 0
fi

# Check if the key starts with "ssh-"
if [[ ! "$1" =~ ^ssh-.* ]]; then
    echo "Error: Invalid public key format. Must start with 'ssh-'."
    exit 1
fi

# Attempt to parse the key with ssh-keygen
ssh-keygen -l -f <(echo "$1") 2> /dev/null

# Check the exit status of ssh-keygen
if [ $? -ne 0 ]; then
    echo "Error: Invalid public key format."
    exit 1
fi

echo "Valid public key detected. Inserting..."
echo "$1" | sudo -u ssh-tun tee -a /etc/tunnel-guard/.ssh/authorized_keys

